management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]

---

spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

